version: '3.8'
services:
 dynamodb-local:
   command: "-jar DynamoDBLocal.jar -sharedDb"
   image: "amazon/dynamodb-local:latest"
   container_name: dynamodb-local
   ports:
     - "8000:8000"
   working_dir: /home/dynamodblocal
   healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost/8000"]
    interval: 5s
    timeout: 3s
    retries: 3