name: security

on:
  push:
    branches:
      - "feat/**"
      - "refactor/**"
      - "fix/**"
    paths:
      - "go.mod"
      - "go.sum"
      - "**/*.go"
  pull_request:
    branches:
      - "main"
  schedule:
    - cron: "0 0 * * 0" # Run every Sunday at 00:00
  workflow_call:
  workflow_dispatch:

permissions: write-all

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: Kesin11/actions-timeline@427ee2cf860166e404d0d69b4f2b24012bb7af4f # v2.2.3

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/golang@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif

      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@6bb031afdd8eb862ea3fc1848194185e076637e5 # v3.28.11
        with:
          sarif_file: snyk.sarif
