name: security

on:
  push:
    branches:
      - "feat/**"
      - "refactor/**"
      - "fix/**"
    paths:
      - "go.mod"
      - "go.sum"
      - "**/*.go"
  pull_request:
    branches:
      - "main"
  schedule:
    - cron: "0 0 * * 0" # Run every Sunday at 00:00
  workflow_call:
  workflow_dispatch:

permissions: write-all

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/golang@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif

      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk.sarif
